/*SGN: CLASS 7*/


/*ONE SAMPLE t TEST*/
/*H0: POPULATION MEAN = SPECIFIED VALUE*/
/*H1: POPULATION MEAN ~= SPECIFIED VALUE*/

PROC TTEST DATA = SASHELP.CLASS H0=14;
VAR AGE;RUN;


/*INDEPENDENT SAMPLE t TEST or 
UNPAIRED t TEST*/
/*H0: MEAN OF VAR IS SAME IN 2 INDEPENDENT*/
/*POPULATIONS*/
/*H1: MEAN OF VAR IS NOT SAME IN 2 INDEPENDENT*/
/*POPULATIONS*/


PROC TTEST DATA = SASHELP.CLASS;
VAR WEIGHT;CLASS SEX;RUN;

/*Here, we first check the p-value for the equality of variances test
If p>0.05, we accept the Ho: Equality of Variances and Check the P-value for 'Pooled' Test
If p < 0.05, we reject Ho: Variances are not equal, and hence the check the p-value for 'Satterthwait' TEST*/


/*****************ONEWAY ANOVA*****************/
PROC ANOVA DATA = SASHELP.PRDSAL3;
CLASS COUNTRY;MODEL ACTUAL = COUNTRY;
MEANS COUNTRY;RUN;




/*PROC ANOVA DATA = SASHELP.PRDSAL3;*/
/*CLASS COUNTRY;MODEL ACTUAL = COUNTRY;*/
/*MEANS COUNTRY; WHERE COUNTRY ~= "Mexico";RUN;*/


/*FOR PAIRWISE COMPARISON TUKEY'S TEST*/


PROC ANOVA DATA = SASHELP.PRDSAL3;
CLASS COUNTRY;MODEL ACTUAL = COUNTRY;
MEANS COUNTRY/TUKEY;RUN;


/*NWAY ANOVA*/
PROC ANOVA DATA = SASHELP.PRDSAL3;
CLASS COUNTRY PRODTYPE;
MODEL ACTUAL = COUNTRY PRODTYPE;
MEANS COUNTRY PRODTYPE;RUN;

/*INTERACTION*/
PROC ANOVA DATA = SASHELP.PRDSAL3;
CLASS COUNTRY PRODTYPE YEAR;
MODEL ACTUAL = 
COUNTRY PRODTYPE COUNTRY*PRODTYPE*YEAR;
MEANS COUNTRY PRODTYPE YEAR;RUN;


/*PAIRED t TEST*/
/*H0: MEAN OF 2 VARIABLES ARE SAME*/
/*H1: MEAN OF 2 VARIABLES ARE NOT SAME*/

PROC TTEST DATA = SASHELP.PRDSAL3;
PAIRED ACTUAL*PREDICT;RUN;



/*PAIRED t TEST AT THE FACTOR LEVEL, DATA NEEDS TO BE SORTED AT THE FACTOR LEVEL*/
/*H0: MEAN OF 2 VARIABLES ARE SAME*/
/*H1: MEAN OF 2 VARIABLES ARE NOT SAME*/


PROC SORT DATA = SASHELP.PRDSAL3 OUT=B01.S1;
BY COUNTRY;RUN;


PROC TTEST DATA = B01.S1;
PAIRED ACTUAL*PREDICT;BY COUNTRY;RUN;



/*FREQUENCY DISTRIBUTION*/
DATA B01.C;SET SASHELP.CLASS;
IF WEIGHT <90 THEN WG = 1;
ELSE WG = 2;RUN;

/*ONE DIMENSION FREQ*/
PROC FREQ DATA = B01.C;TABLES WG SEX;RUN;


/*2 DIMENSION FREQ*/
ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SAS Classes\SGN01\Week5\Freq1.xls";
PROC FREQ DATA = B01.C;TABLES WG*SEX;RUN;
ODS HTML CLOSE;


/*ONLY FREQ*/
PROC FREQ DATA = B01.C;
TABLES WG*SEX/NOROW NOCOL NOPERCENT;RUN;


/*ONLY COL%*/
PROC FREQ DATA = B01.C;
TABLES WG*SEX/NOROW NOFREQ NOPERCENT;RUN;


/*PEARSON'S CHI SQUARE TEST FOR
INDEPENDENCE OF ATTRIBUTES*/
/*H0: THE 2 VARIABLES ARE INDEPENDENTLY*/
/*DISTRIBUTED IN THE POPULATION*/


PROC FREQ DATA = B01.C;
TABLES WG*SEX/NOROW NOPERCENT CHISQ;RUN;
/*PEARSON'S CORRELATION COEFFICIENT*/
/*LINEAR ASSOCIATION B/W 2 CONTINUOUS VAR*/
/*LIES B/W -1 TO + 1*/
/*TEST OF SIGNIFICANCE OF CORR COEFF*/
/*H0: NO CORRL IN THE POPL*/
/*H1: THERE IS CORR IN THE POPL*/
/*IF P < ALPHA THERE IS CORR IN POPL AND */
/*SIGN AND MAGINITUDE OF SAMPEL CORR*/
/*GIVES IDEA ABOUT SIGN AND MAGNITUDE*/
/*OF POPL CORR.*/
/*I P > ALPHA - THERE IS NO CORR IN POPL*/
/*BUT THERE CAN BE NONLINEAR DEPENDENCE*/
/*WHICH NEEDS TO BE VALIDATED USING SCATTER*/
/*PLOT/CORR B/W TRANSFORMED VARIABLES*/

/*B/W ALL NUMERIC VARIABLES*/


PROC CORR DATA = SASHELP.CLASS;RUN;


/*B/W SELECTED NUMERIC VARIABLES*/
PROC CORR DATA = SASHELP.CLASS;
VAR AGE HEIGHT;RUN;

/*WITH SELECTED NUMERIC VARIABLES*/
PROC CORR DATA = SASHELP.CLASS;
VAR AGE HEIGHT;WITH WEIGHT;RUN;


/*SQL IN SAS*/
/*PROC SQL;*/
/*CREATE TABLE DATANAME AS SELECT * FROM*/
/*SOURCE DATA WHERE COND;QUIT;*/


PROC SQL;CREATE TABLE B01.C4 AS SELECT
* FROM SASHELP.CLASS;QUIT;


PROC SQL;CREATE TABLE B01.C4 AS SELECT
NAME,AGE,SEX FROM SASHELP.CLASS;QUIT;

DATA B01.C4;SET SASHELP.CLASS;
KEEP NAME AGE SEX;RUN;


PROC SQL;CREATE TABLE B01.C4 AS SELECT
NAME,AGE,SEX FROM SASHELP.CLASS WHERE
SEX = "F";QUIT;



DATA B01.C4;SET SASHELP.CLASS;
KEEP NAME AGE SEX;IF SEX="F";RUN;


/*GROUPING*/
PROC SUMMARY DATA = SASHELP.CLASS 
MEAN NWAY MISSING;CLASS SEX;
VAR AGE HEIGHT WEIGHT;OUTPUT OUT = B01.C1 
MEAN(AGE) = AVG_AGE MEAN(HEIGHT)=AVG_HT
MEAN(WEIGHT) = AVG_WT;RUN;


PROC SQL;CREATE TABLE B01.C AS SELECT
SEX,COUNT(NAME) AS FREQ,MEAN(AGE) AS AVG_AGE,
MEAN(HEIGHT)AS AVG_HT, MEAN(WEIGHT) AS AVG_WT
FROM SASHELP.CLASS GROUP BY SEX;QUIT;


/*DISTINCT COUNT*/
PROC SQL;CREATE TABLE B01.C AS SELECT
COUNT(DISTINCT(AGE)) AS CN_A, COUNT(DISTINCT(WEIGHT)) AS CN_W
FROM SASHELP.CLASS;QUIT;


PROC SQL;CREATE TABLE B01.C AS SELECT
SEX,COUNT(DISTINCT(AGE)) AS CN 
FROM SASHELP.CLASS GROUP BY SEX;QUIT;


/*JOINS*/

DATA B01.A;SET SASHELP.AIR;M=MONTH(DATE);RUN;
DATA B01.C;SET SASHELP.CLASS;L=_N_;RUN;

PROC SQL;CREATE TABLE B01.M AS SELECT *
FROM B01.A X,B01.C Y WHERE X.M = Y.L;QUIT;


PROC SQL;CREATE TABLE B01.M AS SELECT X.*, Y.NAME,Y.AGE 
FROM B01.A X,B01.C Y 
WHERE X.M = Y.L;QUIT; 		


PROC SQL;CREATE TABLE B01.M AS SELECT X.*,
Y.NAME,Y.AGE FROM B01.A X,B01.C Y 
WHERE X.M = Y.L ORDER BY AGE;QUIT;
