/*-----------------------------------------SGN CLASS 2--------------------------------------------------*/

DATA NEWLIBRARY.NEWDATA;
SET OLDLIBRARY.OLDDATA;
NEW_VAR = FUNCTION(OLD_VAR);
FORMAT VAR <TYPE OF FORAMT>;RUN;

/*STRUCTURE TO CREATE A NEWLIB, NEW DATA,VARIABLE*/

DATA B01.C;SET SASHELP.CLASS;
X = LOG(AGE);RUN;

DATA  B01.C; SET SASHELP.CLASS;
Y=LOG (HEIGHT); RUN; 

DATA B01.C1;SET B01.C;
Y = LOG(HEIGHT);FORMAT X Y 10.2;RUN;
/*W.D format where W~ Width of variable (maximum number of characters including decimals and 
D~ refelects*/
/*NUMERIC FUNCTIONS*/

DATA B01.C1;SET SASHELP.CLASS;
X = LOG(AGE);X10=LOG10(WEIGHT);
WT_SQ = WEIGHT**2;WT_SQT = WEIGHT**0.5;
WT_CB = WEIGHT**3;I=1/AGE;E=EXP(AGE);
R=ROUND(WEIGHT);IT=INT(WEIGHT);
M1=MIN(AGE,HEIGHT,WEIGHT);
M3=MEAN(AGE,HEIGHT,WEIGHT);
M2=MAX(AGE,HEIGHT,WEIGHT);
S=SUM(AGE,HEIGHT,WEIGHT);
ST=STD(AGE,HEIGHT,WEIGHT);
V=VAR(AGE,HEIGHT,WEIGHT);
L = LOG(S)+V/10-M1;
FORMAT X X10 ST 10.2;
FORMAT V L 10.;
RUN;


/*STRING FUNCTIONS*/
DATA B01.C2;SET SASHELP.CLASS;
O=LENGTH(NAME);J = SEX||NAME;
J1 = SEX||" "||NAME;J2 = SEX||"@1234@"||NAME;
K = SEX||AGE;K1 = COMPRESS(SEX||AGE);  
K2 = SEX||STRIP(AGE);K3 = COMPBL(SEX||AGE);	
K4 = SEX||" "||STRIP(AGE); 
K0=COMPRESS(J2,"@12Aa");
U = UPCASE(NAME);L=LOWCASE(NAME);
/*NEW STRING = SUBSTR(STRING,START PT,NO OF CHAR);*/
N = SUBSTR(NAME,1,4);N1 = SUBSTR(NAME,3,3);	
I=INDEX(UPCASE(NAME),"A"); 
S= SCAN(J2,1,"@");S1= SCAN(J2,2,"@"); 
S2= SCAN(J2,3,"@");D=S1*1; 
D1=STRIP(D||"");
RUN;


DATA B01.C3;SET SASHELP.CLASS;
K = SEX||AGE;K1 = COMPRESS(SEX||AGE);
K2= COMPRESS(AGE); 
K3=STRIP(AGE);
RUN;

DATA B01.C6;SET SASHELP.CLASS;
D=SUBSTR(NAME,1,1)||SUBSTR(NAME,3,1)
||SUBSTR(NAME,5,1);
E=SUBSTR(NAME,LENGTH(NAME)-3,4);RUN;


/*DATE FUNCTIONS*/

DATA B01.C4;SET SASHELP.AIR;
FORMAT K DDMMYY10.;
K=DATE; RUN;


DATA B01.C5;SET SASHELP.AIR;
FORMAT K WEEKDATE30.;
FORMAT D E F F1 F2 F3 T DDMMYY10.;
K = DATE;A=DAY(K);B=MONTH(K);
C=YEAR(K);Q=QTR(K);W=WEEKDAY(K);
D=MDY(B,A,C);E=D+40; 
/*NEW DATE = */
/*INTNX("UNIT",START DATE,NO OF UNITS,OPTION);*/
F= INTNX("MONTHS",E,3);
F1=INTNX("MONTHS",E,3,'E');
F2=INTNX("MONTHS",E,3,'S');
F3=INTNX("WEEKS",E,-7,'S');
T=TODAY();
/*DIF=INTCK("UNITS",DATE1,DATE2);*/
C1=INTCK("WEEKS",E,F2);C2=INTCK("DAYS",E,F2);
X=F2-E;RUN;

DATA B01.C5;SET SASHELP.AIR;
FORMAT K WEEKDATE30.;
FORMAT D E F F1 F2 F3 T DDMMYY10.;
K = DATE;A=DAY(K);B=MONTH(K);
C=YEAR(K);Q=QTR(K);W=WEEKDAY(K);
D=MDY(B,A,C);E=D+40;
/*NEW DATE = */
/*INTNX("UNIT",START DATE,NO OF UNITS,OPTION);*/
F= INTNX("MONTHS",E,3);
F1=INTNX("MONTHS",E,3,'E');
F2=INTNX("MONTHS",E,3,'S');
F3=INTNX("WEEKS",E,-7,'S');
T=TODAY();
/*DIF=INTCK("UNITS",DATE1,DATE2);*/
C1=INTCK("WEEKS",E,F2);C2=INTCK("DAYS",E,F2);
X=F2-E;RUN;


/*.KEEP AND DROP VARIABLES*/
DATA B01.C;SET SASHELP.CLASS;KEEP NAME AGE SEX;RUN;

DATA B01.C;SET SASHELP.CLASS;DROP AGE SEX;RUN;

DATA B01.C(DROP =AGE SEX);SET SASHELP.CLASS;RUN;

DATA B01.C(KEEP = NAME AGE SEX);SET SASHELP.CLASS;RUN;
/*EFFICIENT WAY OF KEEPING AND DROPPING VARS*/



/*.RENAME AND LABEL OF VAR*/
DATA B01.C;SET SASHELP.CLASS;RENAME SEX= GENDER;
LABEL AGE = "AGE OF THE STUDENTS";RUN;

/*CLASS ACTIVITY:*/
/*Q1.From SASHELP COMPANY data,
i) create a new dataset with keeping the Level1, Level 2 and Job1
ii)create a new dataset dropping the levels level 5 and Dept Head
iii)Repeat i and rename Level1 as First Level with label Designation*/


DATA B01.C4(KEEP =LEVEL2 LEVEL1 JOB1); SET SASHELP.COMPANY;RUN;
DATA B01.C4(DROP = LEVEL5 Depthead);SET SASHELP.COMPANY; RUN;

DATA B01.C5; SET B01.C4;
RENAME JOB1= JOB; LABEL LEVEL1= "FIRST LEVEL";RUN;
\

/*. LOOKING AT THE STRUCTURE OF THE DATA*/
PROC CONTENTS DATA = B01.C;RUN;

PROC CONTENTS DATA = SASHELP.CITIDAY;RUN; 


/*.TO PRINT THE TITLE & FOOTNOTE*/
TITLE "@ DELHI IVY";FOOTNOTE "BATCH 01";
/*MULTIPLE LINES*/
TITLE1 "@DELHI IVY";TITLE2 "SAS BATCH";
FOOTNOTE1 "BATCH 01";FOOTNOTE2 "CLASS 3 ACTIVITY";

PROC CONTENTS DATA = SASHELP.CITIDAY;
TITLE "1ST PROC LEARNT";
FOOTNOTE "MAY 13th, 2017";RUN;

/*ERASE FROM MEMORY*/
TITLE;FOOTNOTE;	RUN;
