
/*SGN*/
/*********CLASS 6********/


/**********************************************
************MULTIPLE FILE OPERATION*************
**********************************************/


/*DISINTEGRATION OF FILES IN SAS*/

/**********ONLY ONE SUBSET********************/


DATA B01.F;SET SASHELP.CLASS;IF SEX="F";
KEEP NAME AGE SEX;RUN;


/**********TWO SUBSET********************/


DATA B01.F B01.M;SET SASHELP.CLASS;
IF SEX="F" THEN OUTPUT B01.F;
ELSE OUTPUT B01.M;KEEP NAME AGE SEX;RUN;



/**********TWO SUBSET WITH SPECIFIC VARIABLES********************/

DATA B01.F(KEEP=NAME AGE SEX)
B01.M(KEEP =NAME WEIGHT SEX);
SET SASHELP.CLASS;
IF SEX="F" THEN OUTPUT B01.F;
ELSE OUTPUT B01.M;RUN;


/**********CLASS ACTIVITY 1********************/


DATA B01.Q1 B01.Q2 B01.Q3 B01.Q4;
SET SASHELP.AIR;
IF QTR(DATE) = 1 THEN OUTPUT B01.Q1;
ELSE IF QTR(DATE) = 2 THEN OUTPUT B01.Q2;
ELSE IF QTR(DATE) = 3 THEN OUTPUT B01.Q3;
ELSE OUTPUT B01.Q4;RUN;



DATA B01.Q; SET SASHELP.AIR; 
Q= QTR(DATE); RUN; 


DATA B01.Q1 B01.Q2 B01.Q3 B01.Q4;
SET B01.Q;
IF Q = 1 THEN OUTPUT B01.Q1;
ELSE IF Q = 2 THEN OUTPUT B01.Q2;
ELSE IF Q = 3 THEN OUTPUT B01.Q3;
ELSE OUTPUT B01.Q4; RUN;

/**********************************************
***********APPENDING SAS DATA SETS*************
**********************************************/

/*APPENDING*/

DATA B01.Y;SET B01.Q1 B01.Q2 B01.Q3 B01.Q4;RUN;


/*APPENDING WITH CONDITION*/

DATA B01.Y;SET B01.Q1 B01.Q2 B01.Q3 B01.Q4;
IF YEAR(DATE) > 1955;RUN;


DATA B01.C;SET B01.M B01.F;RUN;


/*MERGING*/
/*ONE TO ONE MERGE*/
DATA B01.C;MERGE SASHELP.AIR SASHELP.CLASS;
RUN;


/*ONE TO MANY MERGE*/
DATA B01.C;SET SASHELP.CLASS;L=_N_;RUN;


DATA B01.A;SET SASHELP.AIR;L=MONTH(DATE);RUN;


DATA B01.C B01.A;SET B01.C B01.A; L=_N_ L=_N_;RUN;

/*SORTING IS REQD BEFORE MERGING*/
PROC SORT DATA = B01.C;BY L;RUN;
PROC SORT DATA = B01.A;BY L;RUN;

DATA B01.M;MERGE B01.A B01.C;BY L;RUN;


/*INTERSECTION: X & Y*/
DATA B01.M;
MERGE B01.A(IN = X) B01.C(IN = Y);
BY L;IF X & Y;RUN;


/*X & NOT(Y)*/
DATA B01.M;MERGE B01.A(IN = X) B01.C(IN = Y);
BY L;IF X & NOT(Y);RUN;

/*NOT(X) & Y*/
DATA B01.M;MERGE B01.A(IN = X) B01.C(IN = Y);
BY L;IF NOT(X) & Y;RUN;

/*X*/
DATA B01.M;MERGE B01.A(IN = X) B01.C(IN = Y);
BY L;IF X;RUN;
/*Y*/
DATA B01.M;MERGE B01.A(IN = X) B01.C(IN = Y);
BY L;IF Y;RUN;



/*YEAR CREATED*/
DATA B01.C1;SET SASHELP.AIR;Y=YEAR(DATE);RUN;
/*YEARLY AVERAGE*/

PROC SUMMARY DATA = B01.C1 NWAY MISSING MEAN;
VAR AIR;CLASS Y;
OUTPUT OUT = B01.M MEAN(AIR)= AVG_AIR;RUN;

/*HOME ACTIVITY: FROM SASHELP.AIR, CREATE A FILE WITH WHICH HAS AVG_AIR variable as the YEARLY AVERAGE OF AIR VAR. */
/*MERGE THE CREATED FILE WITH THE AIR FILE, WITH A ADDITIONAL TAG IN THE MERGE FILE, */
/*TAG = HIGH WHEN  AIR > AVG_AIR*/
/*TAG = LOW WHEN AIR < AVG_AIR*/
