/*CENTRAL TENDENCY: MEAN,MEDIAN,MODE, Q1, Q3*/
/*DISPERSION: VARIANCE, STANDARD DEVIATION,*/
/*COEFFICIENT OF VARIATION - SD/AM*100%*/
/*SKEWNESS,KURTOSIS*/
/**/
/*Positive skew Mean>Median > Mode*/
/*Negative skew Mean<Median <Mode*/
/*SK  > 0 - Positive skew*/
/*Sk < 0 - Negative skew*/
/*Sk  = 0 – Symmetric */



/**********************************************
************Descriptive Statistics*************
**********************************************/


/*DEFAULT PARAMETERS ON ALL NUMERIC VARIABLES*/
PROC MEANS DATA = SASHELP.CLASS;RUN;


/*DEFAULT PARAMETERS ON SELECTED NUMERIC VARIABLES*/
PROC MEANS DATA = SASHELP.CLASS;
VAR AGE WEIGHT;RUN;




/*SELECTED PARAMETERS ON ALL NUMERIC VARIABLES*/
PROC MEANS DATA = SASHELP.CLASS
MEAN MEDIAN;RUN;


ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SAS Classes\SGN01\Week3\PROC.MEANS.XLS";
PROC MEANS DATA = SASHELP.CLASS
	N NMISS MEAN VAR STD CV MEDIAN Q1 Q3
MIN MAX RANGE SUM P1 P5 P10 P90 P95 P99
SKEW KURT;RUN;ODS HTML CLOSE;


/*UNIVARIATE*/
PROC UNIVARIATE DATA = SASHELP.AIR;
VAR AIR;RUN;


/*OUTLIERS*/
/*DETECTION*/
MEAN AND MEDIAN IS DIFFERENT
99% AND MAX VALUE IS DIFFERENT
1% AND MIN VALUE IS DIFFERENT;
/*SCATTER PLOT*/


PROC GPLOT DATA = SASHELP.AIR;
PLOT AIR*DATE;RUN;


EXTREME VALUE LIST(2-3% ON EITHER SIDE);
PROC UNIVARIATE DATA = SASHELP.AIR NEXTROBS = 20;
VAR AIR;RUN;


/*THUMB RULE*/
IF DATA IS NORMAL:
VALUE : > MEAN + 3* STD DEV OR < MEAN - 3* STD DEV
IF DATA IS NOT NORMAL:
VALUE : > Q3 + 1.5*(Q3-Q1) OR
< Q1 - 1.5*(Q3-Q1);
SAMPLING:
1. SIMPLE RANDOM SAMPLING
2. STRATIFIED RANDOM SAMPLING 
3. SYSTEMATIC SAMPLING
4. CLUSTER SAMPLING
5. JUDGEMENT/PURPOSIVE SAMPLING
PARAMETER:
STATISTIC: 
/*REMEDY*/
INVALID DATA - MAKE THEM VALID;
VALID DATA - CANNOT BE MORE THAN 1% OF THE DATA
REMOVE OBSERVATIONS - IF THEY HAVE OUTLIERS
ACROSS MULTIPLE VARIABLES
ELSE WE FLOOR/CAP THEM ;

PROC MEANS DATA = SASHELP.CLASS
MEAN MEDIAN;WHERE SEX = "F";RUN;


PROC MEANS DATA = SASHELP.CLASS
MEAN MEDIAN;WHERE SEX = "M";RUN;


/*BY STATEMENT*/
PROC SORT DATA =SASHELP.CLASS OUT = B01.S;
BY SEX;RUN;

PROC MEANS DATA = B01.S MEAN MEDIAN;BY SEX;RUN;


PROC PRINT DATA = B01.S;BY SEX;RUN;

/*CLASS STATEMENT*/
PROC MEANS DATA = SASHELP.CLASS
MEAN MEDIAN;CLASS SEX;RUN;


/*MULTIPLE VARIABLES*/

DATA B01.S;SET SASHELP.AIR;
Y = YEAR(DATE);Q=QTR(DATE);RUN;


PROC MEANS DATA = B01.S MEAN;VAR AIR;CLASS Y;RUN;

PROC MEANS DATA = B01.S MEAN;VAR AIR;
CLASS Q;RUN;

ODS HTML FILE = "C:\Documents and Settings\STD\Desktop\SAS Classes\SGN01\Week3\Class.Output.xls";
PROC MEANS DATA = B01.S MEAN;VAR AIR;
CLASS Y Q;RUN;
ODS HTML CLOSE;


/*OUTPUT FILE*/
PROC MEANS DATA = B01.S MEAN ;VAR AIR;
CLASS Y Q;OUTPUT OUT = B01.D 
MEAN(AIR) = AVG_AIR;RUN;


/*SUMMARY*/
PROC SUMMARY DATA = B01.S MEAN;VAR AIR;
CLASS Y Q;OUTPUT OUT = B01.D 
MEAN(AIR) = AVG_AIR;RUN;
PROC SUMMARY DATA = B01.S MEAN NWAY MISSING;
VAR AIR;CLASS Y Q;OUTPUT OUT = B01.C11 
MEAN(AIR) = AVG_AIR;RUN;


CORRELATION
TESTING OF HYPOTHESIS:
t TEST - ONE SAMPLE, INDEPENDENT SAMPLE
, PAIRED t TEST
ANOVA: 
CHISQUARE TEST FOR IDENPENDENCE OF
ATTRIBUTES
SAS ANNOTATED OUTPUT: UCLA
