/*1.COLOR CODING IN SAS WINDOW*/
MALMKSMA; 
DATA; LIBNAME
0123456



/*2. CREATE A LIBRARY IN SAS USING CODE*/

LIBNAME B00 "C:\Documents and Settings\STD\Desktop\SAS Classes\SGN01";
RUN;

/*3. SYNTAXES IN SAS*/

DATA;
/*DATA TYPES SYNTAXES ARE PRIMARILY USED TO CREATE AND MODIFY DATA*/


PROC;
/*PROC TYPES SYNTAXES ARE PRIMARILY USED TO EXTRACT INFORMATION FROM THE DATA NOTHING TO DO WITH ALTERATION WITH DATA*/


/*OUTCOME OF EVERY VALID PROC IS GIVEN IN THE OUTPUT WINDOW*/
/*RESULTS HELPS TO NAVIGATE IN THE OUTPUT WINDOW*/
/*LOG IS USED TO CHECK WETHER THE SAS PROGRAM HAS BEEN EXECUTED CORRECTLY OR NOT*/


/*3.IMPORTING FILES IN SAS*/

/*IMPORTING EXCEL FILES*/

PROC IMPORT OUT= B01.EXCEL01 
            DATAFILE= "C:\Documents and Settings\STD\Desktop\SAS Classes
\Others\Input Files\TESTCASA.xls" 
            DBMS=EXCEL REPLACE;
     RANGE="Sheet1$"; 
     GETNAMES=YES;
     MIXED=YES;

     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
RUN;


PROC IMPORT OUT= B01.EXCEL02
DATAFILE= "C:\Documents and Settings\STD\Desktop\SAS Classes\SGN01\Input Files\ExcelData.xls" 
DBMS=EXCEL REPLACE;
     RANGE="Sheet1$"; 
     GETNAMES=YES;
     MIXED=YES;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
RUN;


/*IMPORTING TEXT FILES*/

PROC IMPORT OUT= B01.TXT01 
            DATAFILE= "C:\Documents and Settings\STD\Desktop\SAS Classes
\SGN01\Input Files\TESTCASA123.txt" 
            DBMS=DLM REPLACE;
     DELIMITER='09'x; 
     GETNAMES=YES;
     DATAROW=2; 
RUN;

/*IMPORTING CSV FILES*/

PROC IMPORT OUT= B01.CSV01 
            DATAFILE= "C:\Documents and Settings\STD\Desktop\SAS Classes
\SGN01\Input Files\TESTCASA.csv" 
            DBMS=CSV REPLACE;
     GETNAMES=YES;
     DATAROW=2; 
RUN;



















